# Generated by Django 3.2.16 on 2023-02-23 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_description', models.TextField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_images')),
                ('price', models.IntegerField(default=0)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='core.restaurant')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='service',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='service',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='meal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.meal'),
            preserve_default=False,
        ),
    ]
