# Generated by Django 3.2.16 on 2023-02-09 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='courier',
        ),
        migrations.RemoveField(
            model_name='service',
            name='customer',
        ),
    ]
