# Generated by Django 3.2.16 on 2023-05-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='delivery_choice',
            field=models.CharField(choices=[('same_day', 'Same day delivery'), ('scheduled', 'Scheduled delivery')], default='same_day', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='delivery_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='job',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
