# Generated by Django 3.2.16 on 2023-07-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_restaurant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='delivery_choice',
            field=models.CharField(choices=[('standard', 'Standard Delivery'), ('scheduled', 'Scheduled Delivery'), ('services', 'Services')], default='same_day', max_length=20),
        ),
    ]
