# Generated by Django 3.2.16 on 2023-05-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230512_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
