# Generated by Django 3.2.16 on 2023-07-26 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_job_delivery_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='delivery_choice',
            field=models.CharField(choices=[('standard', 'Standard Delivery'), ('scheduled', 'Scheduled Delivery'), ('services', 'Services')], default='standard', max_length=20),
        ),
    ]
