# Generated by Django 3.2.16 on 2023-02-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_courier_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
