# Generated by Django 3.2.16 on 2023-05-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='courier',
            name='total_reviews',
            field=models.IntegerField(default=0),
        ),
    ]
