# Generated by Django 3.2.16 on 2023-07-26 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_job_delivery_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='delivery_choice',
        ),
    ]
