# Generated by Django 3.2.16 on 2023-03-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_courier_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Processing'), (2, 'Ready'), (3, 'On the way'), (4, 'Delivered')]),
        ),
    ]
