# Generated by Django 3.2.16 on 2023-05-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_job_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='delivery_date_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
