# Generated by Django 3.2.16 on 2023-05-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_job_delivery_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='delivery_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
