# Generated by Django 3.2.16 on 2023-07-30 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_notification_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.job'),
        ),
    ]
