# Generated by Django 3.2.16 on 2023-07-31 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_notification_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='has_spill',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
