# Generated by Django 3.2.16 on 2023-05-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_job_rated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('creating', 'Creating'), ('processing', 'Processing'), ('ready', 'ready'), ('picking', 'Picking'), ('Delivering Order', 'Delivering'), ('completed', 'Completed'), ('reviewed', 'reviewed'), ('canceled', 'Canceled')], default='creating', max_length=20),
        ),
    ]
