# Generated by Django 3.2.16 on 2023-07-31 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20230730_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='paid_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
