# Generated by Django 3.2.16 on 2023-07-31 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20230730_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='delivery_time',
        ),
    ]
