# Generated by Django 3.2.16 on 2023-07-31 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_job_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='scheduled_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
