# Generated by Django 3.2.16 on 2023-08-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='previous_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
