# Generated by Django 3.2.16 on 2023-08-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_job_previous_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='delivery_date_time',
        ),
        migrations.AlterField(
            model_name='job',
            name='service_type',
            field=models.CharField(choices=[('standard', 'Standard Delivery'), ('scheduled', 'Scheduled Delivery')], default='standard', max_length=20),
        ),
    ]
