# Generated by Django 3.2.16 on 2023-08-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20230823_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='arrived_at_destination_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='waiting_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
