# Generated by Django 3.2.16 on 2023-08-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20230824_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='job/signatures/'),
        ),
    ]
