# Generated by Django 3.2.16 on 2023-08-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('creating', 'Creating'), ('processing', 'Processing'), ('ready', 'Ready'), ('picking', 'Picking'), ('arrived', 'Arrived'), ('delivering', 'Delivering'), ('signed', 'Signed'), ('completed', 'Completed'), ('reviewed', 'Reviewed'), ('canceled', 'Canceled')], default='creating', max_length=20),
        ),
    ]
