# Generated by Django 3.2.16 on 2023-10-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
    ]
