# Generated by Django 3.2.16 on 2023-10-08 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
