# Generated by Django 3.2.16 on 2023-10-08 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_job_scheduled_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='insurance',
            field=models.FileField(null=True, upload_to='insurances/'),
        ),
        migrations.AddField(
            model_name='courier',
            name='license',
            field=models.FileField(null=True, upload_to='licenses/'),
        ),
        migrations.AddField(
            model_name='courier',
            name='registration',
            field=models.FileField(null=True, upload_to='registrations/'),
        ),
        migrations.AddField(
            model_name='courier',
            name='resume',
            field=models.FileField(null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='courier',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='core.courier')),
            ],
        ),
    ]
