# Generated by Django 4.1.5 on 2023-01-23 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='street',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
